# Generated by Django 5.1 on 2024-08-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0002_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
