# Generated by Django 5.1 on 2024-08-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0004_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
