# Generated by Django 5.1 on 2024-11-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0008_customer_address_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='billboard_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/store/billboard_pictures/'),
        ),
        migrations.AddField(
            model_name='store',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/store/profile_pictures/'),
        ),
    ]
