# Generated by Django 5.1 on 2024-12-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0011_customer_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='type',
            field=models.CharField(choices=[('supermarket', 'Supermarket'), ('cafe', 'Cafe'), ('stationary', 'Stationary Store'), ('home_decor', 'Home Decor Store')], default='supermarket', max_length=50),
        ),
    ]
