# Generated by Django 5.1 on 2024-12-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0012_store_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='type',
            field=models.CharField(blank=True, choices=[('supermarket', 'Supermarket'), ('cafe', 'Cafe'), ('stationary', 'Stationary Store'), ('home_decor', 'Home Decor Store')], default='store', max_length=50),
        ),
    ]
