# Generated by Django 5.1 on 2024-12-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0013_alter_store_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='type',
            new_name='store_kind',
        ),
    ]
