# Generated by Django 5.1 on 2024-12-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0014_rename_type_store_store_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_kind',
            field=models.CharField(blank=True, choices=[('supermarket', 'Supermarket'), ('cafe', 'Cafe'), ('stationary', 'Stationary Store'), ('home_decor', 'Home Decor Store')], default='store', max_length=50, null=True),
        ),
    ]
