# Generated by Django 5.1 on 2024-12-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0017_alter_store_store_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_kind',
            field=models.CharField(choices=[('supermarket', 'Supermarket'), ('cafe', 'Cafe'), ('stationary', 'Stationary Store'), ('home_decor', 'Home Decor Store'), ('store', 'Store')], default='store', max_length=50),
        ),
    ]
